[project]
name = "ai-eda-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.3",
    "joblib>=1.5.3",
    "kaleido>=1.2.0",
    "matplotlib>=3.10.7",
    "numpy>=2.4.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "plotly>=6.5.0",
    "polars>=1.39.3",
    "psycopg[binary]>=3.3.2",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.24",
    "python-dateutil>=2.9.0.post0",
    "reportlab>=4.4.10",
    "scikit-learn>=1.8.0",
    "statsmodels>=0.14.5",
    "xgboost>=3.1.2",
    "lightgbm>=4.6.0",
    "optuna>=4.6.0",
    "prophet>=1.2.1",
    "pmdarima>=2.0.4",
    "uvicorn[standard]>=0.44.0",
    "xlrd>=2.0.2",
]
